package com.mycompany.bankingapplication;

import java.util.Scanner;

/**
 *
 * @author manan
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        label_usertaken.setVisible(false);
        label_incorrect.setVisible(false);
        label_success.setVisible(false);
        label_deposit_selectaccount.setVisible(false);
        label_deposit_validamount.setVisible(false);
        label_withdraw_selectaccount.setVisible(false);
        label_withdraw_validamount.setVisible(false);
        label_withdraw_insufficient.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_signup = new javax.swing.JDialog();
        label_signup_title = new javax.swing.JLabel();
        label_signup_username = new javax.swing.JLabel();
        textfield_signup_username = new javax.swing.JTextField();
        label_signup_password = new javax.swing.JLabel();
        button_signup_signup = new javax.swing.JButton();
        label_usertaken = new javax.swing.JLabel();
        passwordfield_signup_password = new javax.swing.JTextField();
        frame_account = new javax.swing.JFrame();
        label_account_title = new javax.swing.JLabel();
        label_account_checking = new javax.swing.JLabel();
        label_account_savings = new javax.swing.JLabel();
        label_account_checking_balance = new javax.swing.JLabel();
        label_account_savings_balance = new javax.swing.JLabel();
        button_account_deposit = new javax.swing.JButton();
        button_account_withdraw = new javax.swing.JButton();
        button_account_transactions = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();
        dialog_deposit = new javax.swing.JDialog();
        label_deposit_title = new javax.swing.JLabel();
        label_deposit_toaccount = new javax.swing.JLabel();
        radiobutton_deposit_checking = new javax.swing.JRadioButton();
        radiobutton_deposit_savings = new javax.swing.JRadioButton();
        label_deposit_amount = new javax.swing.JLabel();
        textfield_deposit_amount = new javax.swing.JTextField();
        label_deposit_$ = new javax.swing.JLabel();
        button_deposit_deposit = new javax.swing.JButton();
        label_deposit_validamount = new javax.swing.JLabel();
        label_deposit_selectaccount = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        dialog_logout = new javax.swing.JDialog();
        label_logout_title = new javax.swing.JLabel();
        button_logout_yes = new javax.swing.JButton();
        button_logout_no = new javax.swing.JButton();
        dialog_withdraw = new javax.swing.JDialog();
        label_withdraw_title = new javax.swing.JLabel();
        label_withdraw_toaccount = new javax.swing.JLabel();
        radiobutton_withdraw_checking = new javax.swing.JRadioButton();
        radiobutton_withdraw_savings = new javax.swing.JRadioButton();
        label_withdraw_amount = new javax.swing.JLabel();
        textfield_withdraw_amount = new javax.swing.JTextField();
        label_withdraw_$ = new javax.swing.JLabel();
        button_withdraw_withdraw = new javax.swing.JButton();
        label_withdraw_validamount = new javax.swing.JLabel();
        label_withdraw_selectaccount = new javax.swing.JLabel();
        label_withdraw_insufficient = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dialog_transactions = new javax.swing.JDialog();
        label_account_title1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_transactions = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_transactions1 = new javax.swing.JTextArea();
        label_transactions_savings = new javax.swing.JLabel();
        label_transactions_checking = new javax.swing.JLabel();
        label_title = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        textfield_username = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        button_signup = new javax.swing.JButton();
        label_incorrect = new javax.swing.JLabel();
        label_success = new javax.swing.JLabel();
        passwordfield_password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        dialog_signup.setAlwaysOnTop(true);
        dialog_signup.setBackground(new java.awt.Color(153, 255, 255));
        dialog_signup.setMinimumSize(new java.awt.Dimension(400, 300));

        label_signup_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_signup_title.setText("Sign up");

        label_signup_username.setText("Username");

        label_signup_password.setText("Password");

        button_signup_signup.setBackground(new java.awt.Color(51, 153, 255));
        button_signup_signup.setText("Sign up");
        button_signup_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signup_signupActionPerformed(evt);
            }
        });

        label_usertaken.setForeground(new java.awt.Color(255, 51, 51));
        label_usertaken.setText("Username is taken");
        label_usertaken.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                label_usertakenComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout dialog_signupLayout = new javax.swing.GroupLayout(dialog_signup.getContentPane());
        dialog_signup.getContentPane().setLayout(dialog_signupLayout);
        dialog_signupLayout.setHorizontalGroup(
            dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_signupLayout.createSequentialGroup()
                .addGroup(dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_signupLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(label_signup_title))
                    .addGroup(dialog_signupLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_signup_username)
                            .addComponent(label_signup_password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_signup_username, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordfield_signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialog_signupLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(button_signup_signup))
                    .addGroup(dialog_signupLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(label_usertaken)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        dialog_signupLayout.setVerticalGroup(
            dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_signupLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_signup_title)
                .addGap(18, 18, 18)
                .addGroup(dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_signup_username)
                    .addComponent(textfield_signup_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordfield_signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_signup_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(label_usertaken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_signup_signup)
                .addGap(85, 85, 85))
        );

        frame_account.setBackground(new java.awt.Color(204, 255, 102));
        frame_account.setMinimumSize(new java.awt.Dimension(500, 400));

        label_account_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_account_title.setText("Hello, ");

        label_account_checking.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_account_checking.setText("Checking");

        label_account_savings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label_account_savings.setText("Savings");

        label_account_checking_balance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_account_checking_balance.setText("$");

        label_account_savings_balance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_account_savings_balance.setText("$");

        button_account_deposit.setBackground(new java.awt.Color(102, 153, 255));
        button_account_deposit.setText("Deposit");
        button_account_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_account_depositActionPerformed(evt);
            }
        });

        button_account_withdraw.setBackground(new java.awt.Color(102, 153, 255));
        button_account_withdraw.setText("Withdraw");
        button_account_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_account_withdrawActionPerformed(evt);
            }
        });

        button_account_transactions.setBackground(new java.awt.Color(102, 153, 255));
        button_account_transactions.setText("Transactions");
        button_account_transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_account_transactionsActionPerformed(evt);
            }
        });

        button_logout.setBackground(new java.awt.Color(255, 102, 102));
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frame_accountLayout = new javax.swing.GroupLayout(frame_account.getContentPane());
        frame_account.getContentPane().setLayout(frame_accountLayout);
        frame_accountLayout.setHorizontalGroup(
            frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_accountLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_accountLayout.createSequentialGroup()
                        .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frame_accountLayout.createSequentialGroup()
                                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_account_savings)
                                    .addComponent(label_account_checking))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_account_checking_balance)
                                    .addComponent(label_account_savings_balance)))
                            .addGroup(frame_accountLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(button_account_deposit)
                                .addGap(76, 76, 76)
                                .addComponent(button_account_withdraw)
                                .addGap(74, 74, 74)
                                .addComponent(button_account_transactions)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(frame_accountLayout.createSequentialGroup()
                        .addComponent(label_account_title, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_logout)
                        .addGap(27, 27, 27))))
        );
        frame_accountLayout.setVerticalGroup(
            frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frame_accountLayout.createSequentialGroup()
                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frame_accountLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(label_account_title))
                    .addGroup(frame_accountLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(button_logout)))
                .addGap(89, 89, 89)
                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_account_checking)
                    .addComponent(label_account_checking_balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_account_savings_balance)
                    .addComponent(label_account_savings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(frame_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_account_deposit)
                    .addComponent(button_account_withdraw)
                    .addComponent(button_account_transactions))
                .addGap(57, 57, 57))
        );

        dialog_deposit.setMinimumSize(new java.awt.Dimension(400, 400));

        label_deposit_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_deposit_title.setText("Deposit");

        label_deposit_toaccount.setText("To account:");

        buttonGroup1.add(radiobutton_deposit_checking);
        radiobutton_deposit_checking.setText("Checking");
        radiobutton_deposit_checking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_deposit_checkingActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobutton_deposit_savings);
        radiobutton_deposit_savings.setText("Savings");
        radiobutton_deposit_savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_deposit_savingsActionPerformed(evt);
            }
        });

        label_deposit_amount.setText("Amount:");

        textfield_deposit_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_deposit_amountActionPerformed(evt);
            }
        });

        label_deposit_$.setText("$");

        button_deposit_deposit.setBackground(new java.awt.Color(102, 153, 255));
        button_deposit_deposit.setText("Deposit");
        button_deposit_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deposit_depositActionPerformed(evt);
            }
        });

        label_deposit_validamount.setForeground(new java.awt.Color(255, 51, 51));
        label_deposit_validamount.setText("Enter a valid amount");

        label_deposit_selectaccount.setForeground(new java.awt.Color(255, 51, 51));
        label_deposit_selectaccount.setText("Select an account");

        javax.swing.GroupLayout dialog_depositLayout = new javax.swing.GroupLayout(dialog_deposit.getContentPane());
        dialog_deposit.getContentPane().setLayout(dialog_depositLayout);
        dialog_depositLayout.setHorizontalGroup(
            dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_depositLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_deposit_deposit)
                .addGap(161, 161, 161))
            .addGroup(dialog_depositLayout.createSequentialGroup()
                .addGroup(dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_depositLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(label_deposit_title))
                    .addGroup(dialog_depositLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_deposit_validamount)
                            .addGroup(dialog_depositLayout.createSequentialGroup()
                                .addComponent(label_deposit_amount)
                                .addGap(8, 8, 8)
                                .addComponent(label_deposit_$)
                                .addGap(4, 4, 4)
                                .addComponent(textfield_deposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(dialog_depositLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(label_deposit_toaccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_deposit_selectaccount)
                            .addGroup(dialog_depositLayout.createSequentialGroup()
                                .addComponent(radiobutton_deposit_checking)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiobutton_deposit_savings)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        dialog_depositLayout.setVerticalGroup(
            dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_depositLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(label_deposit_title)
                .addGap(53, 53, 53)
                .addGroup(dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_deposit_toaccount)
                    .addComponent(radiobutton_deposit_checking)
                    .addComponent(radiobutton_deposit_savings))
                .addGap(7, 7, 7)
                .addComponent(label_deposit_selectaccount)
                .addGap(18, 18, 18)
                .addGroup(dialog_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_deposit_amount)
                    .addComponent(textfield_deposit_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_deposit_$))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(label_deposit_validamount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(button_deposit_deposit)
                .addGap(28, 28, 28))
        );

        dialog_logout.setMinimumSize(new java.awt.Dimension(400, 150));

        label_logout_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_logout_title.setText("Log out?");

        button_logout_yes.setBackground(new java.awt.Color(153, 255, 153));
        button_logout_yes.setText("Yes");
        button_logout_yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logout_yesActionPerformed(evt);
            }
        });

        button_logout_no.setText("No");
        button_logout_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logout_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_logoutLayout = new javax.swing.GroupLayout(dialog_logout.getContentPane());
        dialog_logout.getContentPane().setLayout(dialog_logoutLayout);
        dialog_logoutLayout.setHorizontalGroup(
            dialog_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_logoutLayout.createSequentialGroup()
                .addGroup(dialog_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_logoutLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(button_logout_yes)
                        .addGap(81, 81, 81)
                        .addComponent(button_logout_no))
                    .addGroup(dialog_logoutLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(label_logout_title)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        dialog_logoutLayout.setVerticalGroup(
            dialog_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_logoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label_logout_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(dialog_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_logout_yes)
                    .addComponent(button_logout_no))
                .addGap(32, 32, 32))
        );

        dialog_withdraw.setMinimumSize(new java.awt.Dimension(400, 400));

        label_withdraw_title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_withdraw_title.setText("Withdraw");

        label_withdraw_toaccount.setText("From account:");

        buttonGroup2.add(radiobutton_withdraw_checking);
        radiobutton_withdraw_checking.setText("Checking");
        radiobutton_withdraw_checking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_withdraw_checkingActionPerformed(evt);
            }
        });

        buttonGroup2.add(radiobutton_withdraw_savings);
        radiobutton_withdraw_savings.setText("Savings");
        radiobutton_withdraw_savings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_withdraw_savingsActionPerformed(evt);
            }
        });

        label_withdraw_amount.setText("Amount:");

        textfield_withdraw_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_withdraw_amountActionPerformed(evt);
            }
        });

        label_withdraw_$.setText("$");

        button_withdraw_withdraw.setBackground(new java.awt.Color(102, 153, 255));
        button_withdraw_withdraw.setText("Withdraw");
        button_withdraw_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_withdraw_withdrawActionPerformed(evt);
            }
        });

        label_withdraw_validamount.setForeground(new java.awt.Color(255, 51, 51));
        label_withdraw_validamount.setText("Enter a valid amount");

        label_withdraw_selectaccount.setForeground(new java.awt.Color(255, 51, 51));
        label_withdraw_selectaccount.setText("Select an account");

        label_withdraw_insufficient.setForeground(new java.awt.Color(255, 51, 51));
        label_withdraw_insufficient.setText("Insufficient funds");

        javax.swing.GroupLayout dialog_withdrawLayout = new javax.swing.GroupLayout(dialog_withdraw.getContentPane());
        dialog_withdraw.getContentPane().setLayout(dialog_withdrawLayout);
        dialog_withdrawLayout.setHorizontalGroup(
            dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_withdrawLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_withdrawLayout.createSequentialGroup()
                        .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_withdraw_selectaccount)
                            .addGroup(dialog_withdrawLayout.createSequentialGroup()
                                .addComponent(label_withdraw_toaccount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiobutton_withdraw_checking)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiobutton_withdraw_savings))
                    .addGroup(dialog_withdrawLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_withdrawLayout.createSequentialGroup()
                                .addComponent(label_withdraw_amount)
                                .addGap(8, 8, 8)
                                .addComponent(label_withdraw_$)
                                .addGap(4, 4, 4)
                                .addComponent(textfield_withdraw_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialog_withdrawLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_withdraw_withdraw)
                                    .addComponent(label_withdraw_insufficient))))))
                .addGap(94, 94, 94))
            .addGroup(dialog_withdrawLayout.createSequentialGroup()
                .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_withdrawLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(label_withdraw_title))
                    .addGroup(dialog_withdrawLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(label_withdraw_validamount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialog_withdrawLayout.setVerticalGroup(
            dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_withdrawLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label_withdraw_title)
                .addGap(18, 18, 18)
                .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_withdraw_toaccount)
                    .addComponent(radiobutton_withdraw_checking)
                    .addComponent(radiobutton_withdraw_savings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_withdraw_selectaccount)
                .addGap(19, 19, 19)
                .addGroup(dialog_withdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_withdraw_amount)
                    .addComponent(textfield_withdraw_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_withdraw_$))
                .addGap(18, 18, 18)
                .addComponent(label_withdraw_validamount)
                .addGap(18, 18, 18)
                .addComponent(label_withdraw_insufficient)
                .addGap(29, 29, 29)
                .addComponent(button_withdraw_withdraw)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        dialog_transactions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dialog_transactions.setLocation(new java.awt.Point(0, 0));
        dialog_transactions.setMinimumSize(new java.awt.Dimension(500, 300));

        label_account_title1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_account_title1.setText("Transactions");

        textarea_transactions.setEditable(false);
        textarea_transactions.setBackground(new java.awt.Color(153, 255, 255));
        textarea_transactions.setColumns(1);
        textarea_transactions.setRows(5);
        jScrollPane1.setViewportView(textarea_transactions);

        textarea_transactions1.setEditable(false);
        textarea_transactions1.setBackground(new java.awt.Color(153, 255, 255));
        textarea_transactions1.setColumns(1);
        textarea_transactions1.setRows(5);
        jScrollPane2.setViewportView(textarea_transactions1);

        label_transactions_savings.setText("Savings");

        label_transactions_checking.setText("Checking");

        javax.swing.GroupLayout dialog_transactionsLayout = new javax.swing.GroupLayout(dialog_transactions.getContentPane());
        dialog_transactions.getContentPane().setLayout(dialog_transactionsLayout);
        dialog_transactionsLayout.setHorizontalGroup(
            dialog_transactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_transactionsLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(label_transactions_checking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_transactions_savings)
                .addGap(75, 75, 75))
            .addGroup(dialog_transactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(dialog_transactionsLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(label_account_title1)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        dialog_transactionsLayout.setVerticalGroup(
            dialog_transactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_transactionsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_account_title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(dialog_transactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_transactions_checking)
                    .addComponent(label_transactions_savings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_transactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(153, 255, 255));

        label_title.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        label_title.setText("Bank");

        panel_login.setBackground(new java.awt.Color(153, 255, 255));
        panel_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textfield_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textfield_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_usernameActionPerformed(evt);
            }
        });

        label_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_username.setText("Username");

        label_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_password.setText("Password");

        button_login.setBackground(new java.awt.Color(51, 153, 255));
        button_login.setText("Login");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        button_signup.setBackground(new java.awt.Color(51, 153, 255));
        button_signup.setText("Sign up");
        button_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_signupActionPerformed(evt);
            }
        });

        label_incorrect.setForeground(new java.awt.Color(255, 51, 51));
        label_incorrect.setText("Username/Password incorrect");

        label_success.setForeground(new java.awt.Color(0, 153, 0));
        label_success.setText("Login succesful");

        passwordfield_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordfield_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfield_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_password)
                            .addComponent(label_username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_incorrect)
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addComponent(label_success)
                                .addGap(38, 38, 38)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(button_signup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_login)
                .addGap(17, 17, 17))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_username)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_password))
                .addGap(89, 89, 89)
                .addComponent(label_incorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_success)
                .addGap(87, 87, 87)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_signup)
                    .addComponent(button_login))
                .addGap(136, 136, 136))
        );

        jLabel1.setText("made by Manan Mishra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(label_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(label_title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        int p = bank.login(textfield_username.getText(), passwordfield_password.getText());
        if( p != -1){
            label_incorrect.setVisible(false);
            label_success.setVisible(true);
            loggedInPerson = p;
            this.setVisible(false);
            renderAccountWindow();
            
        } else {
            label_incorrect.setVisible(true);
            label_success.setVisible(false);
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signupActionPerformed
        textfield_signup_username.setText("");
        passwordfield_signup_password.setText("");
        dialog_signup.setVisible(true);
    }//GEN-LAST:event_button_signupActionPerformed

    private void button_signup_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_signup_signupActionPerformed
        if(!bank.newUser(textfield_signup_username.getText(), passwordfield_signup_password.getText())){
            label_usertaken.setVisible(true);
            return;
        }
    dialog_signup.setVisible(false);
    }//GEN-LAST:event_button_signup_signupActionPerformed

    private void textfield_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_usernameActionPerformed

    private void label_usertakenComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_label_usertakenComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_label_usertakenComponentHidden

    private void passwordfield_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfield_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfield_passwordActionPerformed

    private void button_account_transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_account_transactionsActionPerformed
        textarea_transactions1.setText("");
        textarea_transactions.setText("");
        for(double i : bank.getPerson(loggedInPerson).getTrans(1)){
            textarea_transactions.setText(textarea_transactions.getText() + "" + i + "\n");
            
        }
        for(double i : bank.getPerson(loggedInPerson).getTrans(2)){
            textarea_transactions1.setText(textarea_transactions1.getText() + "" + i + "\n");
            
        }
        textarea_transactions.setText(textarea_transactions.getText() + "End balance: " + bank.getPerson(loggedInPerson).getBalance1());
        textarea_transactions1.setText(textarea_transactions1.getText() + "End balance: " + bank.getPerson(loggedInPerson).getBalance2());
        dialog_transactions.setVisible(true);
    }//GEN-LAST:event_button_account_transactionsActionPerformed

    private void button_account_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_account_depositActionPerformed
       
        radiobutton_deposit_checking.setSelected(true);
        radiobutton_deposit_savings.setSelected(false);
        textfield_deposit_amount.setText("");
        label_deposit_selectaccount.setVisible(false);
        label_deposit_validamount.setVisible(false);
        dialog_deposit.setVisible(true);
    }//GEN-LAST:event_button_account_depositActionPerformed

    private void radiobutton_deposit_checkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_deposit_checkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_deposit_checkingActionPerformed

    private void radiobutton_deposit_savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_deposit_savingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_deposit_savingsActionPerformed

    private void textfield_deposit_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_deposit_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_deposit_amountActionPerformed

    private void button_deposit_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deposit_depositActionPerformed

        Scanner scanner = new Scanner(textfield_deposit_amount.getText());
        if(scanner.hasNextDouble()){
            if(radiobutton_deposit_checking.isSelected()){
                bank.deposit(loggedInPerson, scanner.nextDouble(), 1);
                dialog_deposit.setVisible(false);
                renderAccountWindow();
                return;
            }
            if(radiobutton_deposit_savings.isSelected()){
                bank.deposit(loggedInPerson, scanner.nextDouble(), 2);
                dialog_deposit.setVisible(false);
                renderAccountWindow();
                return;
            }
            label_deposit_selectaccount.setVisible(true);
            return;
        }
        label_deposit_validamount.setVisible(true);
        
    }//GEN-LAST:event_button_deposit_depositActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        dialog_logout.setVisible(true);
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_logout_yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logout_yesActionPerformed
        frame_account.setVisible(false);
        textfield_username.setText("");
        passwordfield_password.setText("");
        label_success.setVisible(false);
        dialog_logout.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_button_logout_yesActionPerformed

    private void button_logout_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logout_noActionPerformed
        dialog_logout.setVisible(false);
    }//GEN-LAST:event_button_logout_noActionPerformed

    private void radiobutton_withdraw_checkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_withdraw_checkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_withdraw_checkingActionPerformed

    private void radiobutton_withdraw_savingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_withdraw_savingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_withdraw_savingsActionPerformed

    private void textfield_withdraw_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_withdraw_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_withdraw_amountActionPerformed

    private void button_withdraw_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_withdraw_withdrawActionPerformed
        Scanner scanner = new Scanner(textfield_withdraw_amount.getText());
        if(scanner.hasNextDouble()){
            double amount = scanner.nextDouble();
            if(radiobutton_withdraw_checking.isSelected()){
                if(!bank.withdraw(loggedInPerson, amount, 1)){
                    label_withdraw_insufficient.setVisible(true);
                    return;
                }
                
                dialog_withdraw.setVisible(false);
                renderAccountWindow();
                return;
            }
            if(radiobutton_withdraw_savings.isSelected()){
                if(!bank.withdraw(loggedInPerson, amount, 2)){
                    label_withdraw_insufficient.setVisible(true);
                    return;
                }
                
                dialog_withdraw.setVisible(false);
                renderAccountWindow();
                return;
            }
            label_withdraw_selectaccount.setVisible(true);
            return;
        }
        label_withdraw_validamount.setVisible(true);
    }//GEN-LAST:event_button_withdraw_withdrawActionPerformed

    private void button_account_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_account_withdrawActionPerformed
        radiobutton_withdraw_checking.setSelected(true);
        radiobutton_withdraw_savings.setSelected(false);
        textfield_withdraw_amount.setText("");
        label_withdraw_selectaccount.setVisible(false);
        label_withdraw_validamount.setVisible(false);
        label_withdraw_insufficient.setVisible(false);
        dialog_withdraw.setVisible(true);
    }//GEN-LAST:event_button_account_withdrawActionPerformed
    
    private void renderAccountWindow(){
        frame_account.setVisible(false);
        label_account_title.setText("Hello, " + bank.getPerson(loggedInPerson).getUser());
        label_account_checking_balance.setText("$" + bank.getPerson(loggedInPerson).getBalance1());
        label_account_savings_balance.setText("$" + bank.getPerson(loggedInPerson).getBalance2());
        frame_account.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    private int loggedInPerson = -1;
    private final Bank bank = new Bank();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton button_account_deposit;
    private javax.swing.JButton button_account_transactions;
    private javax.swing.JButton button_account_withdraw;
    private javax.swing.JButton button_deposit_deposit;
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_logout_no;
    private javax.swing.JButton button_logout_yes;
    private javax.swing.JButton button_signup;
    private javax.swing.JButton button_signup_signup;
    private javax.swing.JButton button_withdraw_withdraw;
    private javax.swing.JDialog dialog_deposit;
    private javax.swing.JDialog dialog_logout;
    private javax.swing.JDialog dialog_signup;
    private javax.swing.JDialog dialog_transactions;
    private javax.swing.JDialog dialog_withdraw;
    private javax.swing.JFrame frame_account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_account_checking;
    private javax.swing.JLabel label_account_checking_balance;
    private javax.swing.JLabel label_account_savings;
    private javax.swing.JLabel label_account_savings_balance;
    private javax.swing.JLabel label_account_title;
    private javax.swing.JLabel label_account_title1;
    private javax.swing.JLabel label_deposit_$;
    private javax.swing.JLabel label_deposit_amount;
    private javax.swing.JLabel label_deposit_selectaccount;
    private javax.swing.JLabel label_deposit_title;
    private javax.swing.JLabel label_deposit_toaccount;
    private javax.swing.JLabel label_deposit_validamount;
    private javax.swing.JLabel label_incorrect;
    private javax.swing.JLabel label_logout_title;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_signup_password;
    private javax.swing.JLabel label_signup_title;
    private javax.swing.JLabel label_signup_username;
    private javax.swing.JLabel label_success;
    private javax.swing.JLabel label_title;
    private javax.swing.JLabel label_transactions_checking;
    private javax.swing.JLabel label_transactions_savings;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel label_usertaken;
    private javax.swing.JLabel label_withdraw_$;
    private javax.swing.JLabel label_withdraw_amount;
    private javax.swing.JLabel label_withdraw_insufficient;
    private javax.swing.JLabel label_withdraw_selectaccount;
    private javax.swing.JLabel label_withdraw_title;
    private javax.swing.JLabel label_withdraw_toaccount;
    private javax.swing.JLabel label_withdraw_validamount;
    private javax.swing.JPanel panel_login;
    private javax.swing.JTextField passwordfield_password;
    private javax.swing.JTextField passwordfield_signup_password;
    private javax.swing.JRadioButton radiobutton_deposit_checking;
    private javax.swing.JRadioButton radiobutton_deposit_savings;
    private javax.swing.JRadioButton radiobutton_withdraw_checking;
    private javax.swing.JRadioButton radiobutton_withdraw_savings;
    private javax.swing.JTextArea textarea_transactions;
    private javax.swing.JTextArea textarea_transactions1;
    private javax.swing.JTextField textfield_deposit_amount;
    private javax.swing.JTextField textfield_signup_username;
    private javax.swing.JTextField textfield_username;
    private javax.swing.JTextField textfield_withdraw_amount;
    // End of variables declaration//GEN-END:variables
}
